"""
actions.py - The calls the view's controls make, so frames don't depend on the whole Controller.
"""
from typing import Protocol


class ViewActions(Protocol):
    # Setup screen
    def change_name(self, name: str) -> None: ...
    def set_level(self, level: int) -> None: ...
    def equip_weapon(self, name: str) -> None: ...
    def equip_armor(self, name: str) -> None: ...
    def equip_shield(self, name: str) -> None: ...
    def buy_herb(self) -> None: ...
    def select_enemy(self, name: str) -> None: ...
    def start_battle(self) -> None: ...

    # Battle screen
    def attack(self) -> None: ...
    def use_herb(self) -> None: ...
    def flee(self) -> None: ...
    def cast_spell(self, label: str) -> None: ...
